apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: velero-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: gitops
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: velero-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        image: registry.gitlab.com/zestlabs-io/education/curriculum/golearning-velero-operator:v0.1
        command:
        - /manager
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "velero-operator"
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: velero-registry-credentials