apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: veleros.backup.go-learning.com
spec:
  group: backup.go-learning.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                provider:
                  type: string
                bucket:
                  type: string
                region:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
  scope: Namespaced
  names:
    plural: veleros
    singular: velero
    kind: Velero
    shortNames:
    - v
