# permissions for end users to view veleroes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: velero-operator
    app.kubernetes.io/managed-by: kustomize
  name: velero-viewer-role
rules:
- apiGroups:
  - backup.go-learning.com
  resources:
  - veleroes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.go-learning.com
  resources:
  - veleroes/status
  verbs:
  - get
